import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    lunchmenu: "lunch menu",
    notAvYet: "Not available yet",
    notAv: "Not available",
    noServing: "No serving on this day",
    mo: "Mo",
    tu: "Tu",
    we: "We",
    th: "Th",
    fr: "Fr",
    sa: "Sa",
    partiesHeader: "Student parties in Metropolitan area",
    noParties: "No parties on selected day",
    commonLinks: "Common links",
    studentsGuide: "Students' guide",
    laura: "Jobsteaser",
    zone: "Zone sports",
    groupid: "Group id",
    timetablefor: "Timetable for",
    lukkari: "",
    eg: "e.g Tn2pd",
    scroll: "Scroll to see other days",
    moodleHelpText: "Click on course to open it's Moodle",
    partyName: "Party name",
    ticketsLeft: "Tickets left",
    allergens: "Allergens",
    cafeteriaButton: "Show cafeteria queue",
    searchButton: "Search",
    feedBackText: "Give feedback!"
  },
  fi: {
    lunchmenu: "lounaslista",
    notAvYet: "Ei saatavilla vielä",
    notAv: "Ei saatavilla",
    noServing: "Ei tarjoilua valittuna päivänä",
    mo: "Ma",
    tu: "Ti",
    we: "Ke",
    th: "To",
    fr: "Pe",
    sa: "La",
    partiesHeader: "Opiskelijajuhlat Pääkaupunkiseudulla",
    noParties: "Ei juhlia valittuna päivänä",
    commonLinks: "Muita yleisiä linkkejä",
    studentsGuide: "Opinto-opas",
    laura: "Laura työpaikat",
    zone: "Zone urheilu",
    groupid: "Ryhmätunnus",
    timetablefor: "Ryhmän",
    lukkari: "lukujärjestys",
    eg: "e.g Tn2pd",
    scroll: "Liu’uta nähdäksesi muut päivät",
    moodleHelpText: "Klikkaa kurssia avataksesi sen Moodlesivu",
    partyName: "Juhlan nimi",
    ticketsLeft: "Lippuja jäljellä",
    allergens: "Allergeenit",
    cafeteriaButton: "Näytä ruokalan jono",
    searchButton: "Hae",
    feedBackText: "Anna palautetta!"
  }
});

export default strings;
